# Math dataset prompt configuration
name: "math"
description: "Configuration for math datasets with numerical answers"
task: "Your task is to assist in solving a math reasoning problem by providing
  a clear and detailed solution."
# System prompt for the solver
system_prompt: >-
  You are a helpful assistant with expertise in mathematics and reasoning.
  Your task is to assist in solving a math reasoning problem by providing
  a clear and detailed solution. Limit your output within 100 words,
  and your final answer should be a single numerical number,
  in the form of {{answer}}, at the end of your response.
  For example, 'The answer is {{42}}.'

# Answer pattern (regex to extract the answer)
answer_pattern: "\\{\\{(\\-?\\d+(\\.\\d+)?)\\}\\}"

# Answer format instruction
answer_format_instruction: >-
  Your final answer should be a single numerical number,
  in the form of {{answer}}, at the end of your response.
  For example, 'The answer is {{42}}.'
